### ISSUE TITLE
no such file to load -- spice/chef (LoadError)

### ISSUE THREAD

**Issue by ghost** [danryan/spice#14]
Hi. I built the gem from git but received this error when running my program with the spice require:

no such file to load -- spice/chef (LoadError)

I read the git log and this class was removed, but the require is still present.

I commented out  require 'spice/chef' in gems/spice-1.0.0.pre/lib/spice.rb, also removed Spice.connect! from my program and all is well, able to talk to opscode. I am pretty weak when it comes to using git and it drives me nuts as I know it is sanity saver. Using this for easy practice I forked the repo and made my fantastical one line fix.  :)

Thank you,

Bryan

**Comment by danryan** [comment]
Thanks for reporting this! I just released the GA version (now 1.0.2), which should resolve this issue.
