### ISSUE TITLE
Opscode: client_error.rb:16:in `on_complete': Spice::Error::NotFound

### ISSUE THREAD

**Issue by ghost** [danryan/spice#19]
Hi, I have been out of this for a while. I'm behind and everything is updated. I am trying to interface to my opscode account. I get  client_error.rb:16:in `on_complete': Spice::Error::NotFound when attempting to run simple spice script. 
What am I doing wrong? 

Thank you,
Bryan

```
$ knife -v
Chef: 10.13.0
```

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 1.8.24
  - RUBY VERSION: 1.8.7 (2011-12-28 patchlevel 357) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/tightwork/.gem/ruby/1.8
  - RUBY EXECUTABLE: /usr/bin/ruby18
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/tightwork/.gem/ruby/1.8
     - /usr/local/lib64/ruby/gems/1.8
     - /usr/lib64/ruby/gems/1.8
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :benchmark => false
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - http://rubygems.org/
```

```
$ gem list spice

*** LOCAL GEMS ***

spice (1.0.3)
```

``` Ruby
#!/usr/bin/env ruby

require 'rubygems'
require 'spice'

Spice.server_url = "https://api.opscode.com/organizations/me"
Spice.client_name = "chef-validator"
Spice.client_key = Spice.read_key_file("/home/tightwork/.chef/chef-validator.pem")
Spice.chef_version = "10.13.0"
Spice.clients
```

```
$ ./script.rb 
/usr/local/lib64/ruby/gems/1.8/gems/spice-1.0.3/lib/spice/response/client_error.rb:16:in `on_complete': Spice::Error::NotFound
    from /usr/local/lib64/ruby/gems/1.8/gems/faraday-0.8.1/lib/faraday/response.rb:9:in `call'
    from /usr/local/lib64/ruby/gems/1.8/gems/faraday-0.8.1/lib/faraday/response.rb:63:in `on_complete'
    from /usr/local/lib64/ruby/gems/1.8/gems/faraday-0.8.1/lib/faraday/response.rb:8:in `call'
    from /usr/local/lib64/ruby/gems/1.8/gems/faraday-0.8.1/lib/faraday/response.rb:8:in `call'
    from /usr/local/lib64/ruby/gems/1.8/gems/faraday-0.8.1/lib/faraday/connection.rb:226:in `run_request'
    from /usr/local/lib64/ruby/gems/1.8/gems/spice-1.0.3/lib/spice/request.rb:54:in `request'
    from /usr/local/lib64/ruby/gems/1.8/gems/spice-1.0.3/lib/spice/request.rb:11:in `get'
    from /usr/local/lib64/ruby/gems/1.8/gems/spice-1.0.3/lib/spice/connection/search.rb:34:in `search'
    from /usr/local/lib64/ruby/gems/1.8/gems/spice-1.0.3/lib/spice/connection/clients.rb:11:in `clients'
    from /usr/local/lib64/ruby/gems/1.8/gems/spice-1.0.3/lib/spice.rb:20:in `send'
    from /usr/local/lib64/ruby/gems/1.8/gems/spice-1.0.3/lib/spice.rb:20:in `method_missing'
    from ./script.rb:10
```

**Comment by danryan** [comment]
Hey Bryan,

Your configuration and usage looks good. Looks like I broke support for the hosted platform. I'm able to duplicate your findings. I'll debug things on my end, fix up what's wrong, and push out a new version. Thanks for the report!

**Comment by pid1co** [comment]
Just wanted to add my voice to this issue.  I am in the same boat, using a very similiar config, I also get Spice::Error:NotFound when trying to pull things from the hosted platform

**Comment by pid1co** [comment]
I did a little investigating on this.  I believe the problem is in Spice::Request
In #request(method, path, params, options).  uri.path should be /organizations<org> but instead your appending the search query to URI.path.  So when someone uses server_url of https://api.opscode.com/organization/<org>, its being overwritten by uri += path.  Also URI.query will automatically add the '?' operator to the query field so you dont have to pass it in on the path. 

I have not had time to muck around much but i think if you add another attribute to spice e.g. DEFAULT_SERVERDIR and then use that in you request, get put methods it should work.  I am guessig there is a bit more refactoring to do as all of the methods in connection/ directory use get() to query the chef server.  

Hope that makes sense, I am only an amateur ruby developer :)

**Comment by Gurpartap** [comment]
Any update?

**Comment by Gurpartap** [comment]
Instead of `Spice.clients` or `Spice.get("/clients")`, this will work:

`Spice.get("/organizations/ORGNAME/clients")`

The problem, as apparent from the fix above, is that spice is truncating the `/organizations/ORGNAME` part from the server url, which is required for hosted chef from opscode.

**Comment by ghost** [comment]
@Gurpartap  yes that works, thank you!

I believe this problem and what @ianand0204 is referring to is the code around line 45; in request.rb:

``` ruby

def request(method, path, params, options)
      json_params = params ? MultiJson.dump(params) : ""
      uri = server_url
      uri = URI(uri) unless uri.respond_to?(:host)
      uri += path

      headers = signature_headers(method.to_s.upcase.to_sym, uri.path, json_params)
```

**Comment by ghost** [comment]
Unfortunately still breaking use of data bags since that method does not seem to take the path to the org. Get the same error.   :-/

Faraday is another gem to learn about, so don't anybody wait for me. :)

**Comment by danryan** [comment]
@tightwork @Gurpartap @ianand0204 This issue is fixed thanks to the amazing work of @cgriego. I'm so sorry for the delay folks. Sometimes life gets in the way of open source :)

**Comment by Gurpartap** [comment]
:satisfied:
