### ISSUE TITLE
When using Bundler w/ HEAD

### ISSUE THREAD

**Issue by portertech** [danryan/spice#4]
Gemfile:

gem 'chef'
gem 'spice', :git => 'git://github.com/danryan/spice.git'

Require:

require 'bundler/setup'
Bundler.require(:default)

/Users/jinx/.rvm/gems/ruby-1.8.7-p302/bundler/gems/spice-066b1e5a124f/lib/spice/authentication.rb:3:in `require': no such file to load -- chef/version (LoadError)
    from /Users/jinx/.rvm/gems/ruby-1.8.7-p302/bundler/gems/spice-066b1e5a124f/lib/spice/authentication.rb:3
    from /Users/jinx/.rvm/gems/ruby-1.8.7-p302/bundler/gems/spice-066b1e5a124f/lib/spice.rb:5:in`require'
    from /Users/jinx/.rvm/gems/ruby-1.8.7-p302/bundler/gems/spice-066b1e5a124f/lib/spice.rb:5
    from /Users/jinx/.rvm/gems/ruby-1.8.7-p302/gems/bundler-1.0.10/lib/bundler/runtime.rb:68:in `require'
    from /Users/jinx/.rvm/gems/ruby-1.8.7-p302/gems/bundler-1.0.10/lib/bundler/runtime.rb:68:in`require'
    from /Users/jinx/.rvm/gems/ruby-1.8.7-p302/gems/bundler-1.0.10/lib/bundler/runtime.rb:66:in `each'
    from /Users/jinx/.rvm/gems/ruby-1.8.7-p302/gems/bundler-1.0.10/lib/bundler/runtime.rb:66:in`require'
    from /Users/jinx/.rvm/gems/ruby-1.8.7-p302/gems/bundler-1.0.10/lib/bundler/runtime.rb:55:in `each'
    from /Users/jinx/.rvm/gems/ruby-1.8.7-p302/gems/bundler-1.0.10/lib/bundler/runtime.rb:55:in`require'
    from /Users/jinx/.rvm/gems/ruby-1.8.7-p302/gems/bundler-1.0.10/lib/bundler.rb:120:in `require'
    from dashboard.rb:62

**Comment by portertech** [comment]
nvm, it was using an old version of chef on my local. 

specified 0.9.14 in the gem file, working now.

**Comment by danryan** [comment]
Hi there, 'chef/version' isn't available on older versions of chef (go figure, eh? :D), so I need to consider a different alternative that works across all systems. 

Thanks much for the report! Glad to see it confirmed on another system.
